name: generate_23-059
on:
  schedule:
    - cron:  '30 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    container: metanorma/metanorma:1.6.4
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          path: main
      - name: checkout other repo
        uses: actions/checkout@v3 # checkout the repository content to github runner
        with:
          repository: opengeospatial/developer-events
          path: 23-059
      - name: Generate document
        run: |
          cd 23-059/2023/Open-Standards-Code-Sprint/engineering-report
          metanorma compile --agree-to-terms -t ogc -x xml,html document.adoc
          cp document.html ../../../../main/23-059.html
          cd ../../../../main
          git config --global user.name 'opengeospatial'
          git config --global user.email 'opengeospatial@users.noreply.github.com'
          git add 23-059.html
          git commit -am "Automated generation of HTML documents"
          git push
